twig:
    globals:
        order_domain: 'http://127.0.0.1:8000/order/'
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
